<a href="https://colab.research.google.com/github/Mowee0/LinearAlgebra_2ndSem/blob/main/Assignment_3_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
## Laboratory 4: Matrices 
### Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

## Objectives
### At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations
2. Perform basic matrix operations
3. Program and translate matrix equations and operations using Pythons

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrics
(own discussion)
The notation and use of matrices is probably one of the fundamentals of moderm computing. Matrices are also handy represntations of complex equations or multiple inter-related equations from 2-dimensional equations to even hunderds and thousands of them.

Let's say for example you have *A* and *B* as system of equation.



$$
A = \left\{
    \begin{array}\
        3x + 2y \\ 
        5x - 8y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        2x+9y+8z \\ 
        12x -34y -5z \\
        -5x + 43y +24z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w+3x+6y+9z \\ 
        w+12x -15y -18z \\
        w+-21x + 24y +27z
    \end{array}
\right. \\
D = \left\{
    \begin{array}\
        v+w+4x+8y+12z \\ 
        v+w+16x -20y -24z \\
        v+w+-28x + 32y +36z
    \end{array}
\right. $$

We could see that *A* is a system of 2 equations with 2 parameters. While *B* is a system of 3 equations with 3 parameters. *C* is a system with 4 equations and 4 variables and lastly, *D* is a system with 5 equations and 5 variables. We can represent them as matrices as:

$$
A=\begin{bmatrix} 3 & 2 \\ 5 & -8\end{bmatrix} \\
B=\begin{bmatrix} 2 & 9 & 8 \\ 12 & -34 & -5 \\ -5 & 43 & 24\end{bmatrix} \\
C=\begin{bmatrix} 1 & 3 & 6 & 9\\ 1& 12 & 15 & 18 \\ 1 & 21 & 24 &27\end{bmatrix} \\
D=\begin{bmatrix} 1 & 1 & 4 & 8 & 12\\ 1 & 1 & 16 & 20 & 24 \\ 1& 1 & 28 & 32 &36\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrcices, their types, and operations. We'll proceed in doing them here in Python

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
Do note that the $size$ of a matrix is $i\times j$.

###Declaring Matrices

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using <b>shape</b>, <b>dimensions</b> and <b>size</b> attributes, we'll use them to analyze these matrices.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [7, 8],
    [9, 10]
])
describe_mat(A)

Matrix:
[[ 7  8]
 [ 9 10]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [11,12],
    [13,14]
])
describe_mat(G)

Matrix:
[[11 12]
 [13 14]]

Shape:	(2, 2)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [14, 15],
    [16, 17],
    [18, 19]
])
describe_mat(B)

Matrix:
[[14 15]
 [16 17]
 [18 19]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([3,6,9,12,15])
describe_mat(H)

Matrix:
[ 3  6  9 12 15]

Shape:	(5,)
Rank:	1



## Categorizing Matrices
There are several ways of classifying matrices. Once could be according to their **shape** and another is according to their **element values**. We'll try to go through them.

#### According to Shape

##### Rows and Columns 

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



##### Square matrices
Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2



#### According Element Values

##### Null Matrix
A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


##### Zero Matrix
A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##### Ones Matrix
A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##### Diagonal Matrix
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

False

##### Identity Matrix 
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### Upper Triangle Matrix 
An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

##### Lower Triangle Matrix
A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

**Answer**

In [ ]:
num_1 = np.array([
    [5, 3, -1]
])
print (num_1)

[[ 5  3 -1]]


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

**Answer**

In [ ]:
num_2 = np.array([
    [1,2,1],
    [0,4,-1,],
    [0,0,10]
])
describe_mat(num_2)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown and as a LaTeX markdown.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


**Answer**

Linear Combination:
$$
G = \left\{\begin{array}
1x_1 + 7x_2 +8x_3\\
2x_1 + 2x_2 +2x_3\\
4x_1 + 6x_2 +7x_3
\end{array}\right.
$$
LaTeX:
$$
G =\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix} \\
$$

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

**Answer**

Linear Combination:
$$
H = \left\{\begin{array}
1x_1 \\
2x_1 + 2x_2\\
4x_1 + 6x_2 +7x_3
\end{array}\right.
$$
LaTeX:
$$
H=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix} \\
$$

## Matrix Algebra

### Addition

In [ ]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

In [ ]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

### Subtraction

In [ ]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-Wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [ ]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [ ]:
A@B

ValueError: ignored

The reason behind the error is because matrix **A** is (3x2) and matrix **B** is also (3x2). It would be undefined.

## Activity

### Task 1

Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.
Displays whether the matrix is square or non-square.
Displays whether the matrix is an empty matrix.
Displays if the matrix is an identity, ones, or zeros matrix
Use 3 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [1]:
## Function area

import numpy as np

In [2]:
## Matrix declarations

def mat_desc(matrix):
  if matrix.size >0:
    is_square= True if matrix.shape[0] == matrix.shape[1] else False
    print (f'{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSquare:\t{is_square}\nMatrix is not Null')
  else:
    print ('Matrix is Null')

In [3]:
## Test Areas

mat_1= np.ones((6,6,))

print('Matrix 1:')
mat_desc(mat_1)

result = np.all((np.identity(6)))
if result:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

result = np.all((mat_1 == 1))
if result:
  print('Ones Matrix')
else:
  print('Contains non-one element')

result = np.all((mat_1 == 0))
if result:
  print('Zero Matrix')
else:
  print('Contains non-zero element')

Matrix 1:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Shape:	(6, 6)
Rank:	2
Square:	True
Matrix is not Null
Not an Identity Matrix
Ones Matrix
Contains non-zero element


In [4]:
## Test Areas

mat_2= np.zeros((5,10))
print('Matrix 2:')
mat_desc(mat_2)

result = np.all((np.identity(5)))
if result:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

result = np.all((mat_2 == 1))
if result:
  print('Ones Matrix')
else:
  print('Contains non-one element')

result = np.all((mat_2 == 0))
if result:
  print('Zero Matrix')
else:
  print('Contains non-zero element')

Matrix 2:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Shape:	(5, 10)
Rank:	2
Square:	False
Matrix is not Null
Not an Identity Matrix
Contains non-one element
Zero Matrix


In [5]:
## Test Areas

mat_3= np.array ([   
                  [13,67,89,90,67,55,99],
                  [55,78,6,33,900,0,3],
                  [21,34,5,88,93,87,54],
                  [27,76,98,0,96,26,37],
                  [4,5,3,9,2,8,9],
                  [25,30,11,3,1,27,8],
                  [13,69,0,65,7,8,45]         
])
print('Matrix 3:')
mat_desc(mat_3)

result = np.all((np.identity(7)))
if result:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

result = np.all((mat_3 == 1))
if result:
  print('Ones Matrix')
else:
  print('Contains non-one element')

result = np.all((mat_3 == 0))
if result:
  print('Zero Matrix')
else:
  print('Contains non-zero element')

Matrix 3:
[[ 13  67  89  90  67  55  99]
 [ 55  78   6  33 900   0   3]
 [ 21  34   5  88  93  87  54]
 [ 27  76  98   0  96  26  37]
 [  4   5   3   9   2   8   9]
 [ 25  30  11   3   1  27   8]
 [ 13  69   0  65   7   8  45]]

Shape:	(7, 7)
Rank:	2
Square:	True
Matrix is not Null
Not an Identity Matrix
Contains non-one element
Contains non-zero element


### Task 2
Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [7]:
def mat_operations(matrix):
  print (f'{matrix}')

In [8]:
R4 = int(input('Enter the number of rows: '))
C4 = int(input('Enter the number of columns: '))

print('\nEnter',R4*C4,'values for Matrix 1\n\t(NOTE: Use space for separating the numbers)\n\t(NOTE:Your first',C4,' number/s would be the first row):')
m4 = list(map(int, input().split()))
mat_4 = np.array(m4).reshape(R4, C4)
print('\nMatrix 4 is:')
mat_operations(mat_4)

print('----------------------------------------------')

R5 = int(input('Enter the number of rows: '))
C5 = int(input('Enter the number of columns: '))

print('\nEnter',R5*C5,'values for Matrix 1\n\t(NOTE: Use space for separating the numbers)\n\t(NOTE: Your first',C5,' number/s would be the first row):')
m5 = list(map(int, input().split()))
mat_5 = np.array(m5).reshape(R5, C5)
print('\nMatrix 5 is:')
mat_operations(mat_5)

print('----------------------------------------------')

R6 = int(input('Enter the number of rows: '))
C6 = int(input('Enter the number of columns: '))

print('\nEnter',R6*C6,'values for Matrix 1\n\t(NOTE: Use space for separating the numbers)\n\t(NOTE: Your first',C6,' number/s would be the first row):')
m6 = list(map(int, input().split()))
mat_6 = np.array(m6).reshape(R6, C6)
print('\nMatrix 6 is:')
mat_operations(mat_6)

print('----------------------------------------------')

R7 = int(input('Enter the number of rows: '))
C7 = int(input('Enter the number of columns: '))

print('\nEnter',R7*C7,'values for Matrix 1\n\t(NOTE: Use space for separating the numbers)\n\t(NOTE: Your first',C7,' number/s would be the first row):')
m7 = list(map(int, input().split()))
mat_7 = np.array(m7).reshape(R7, C7)
print('\nMatrix 7 is:')
mat_operations(mat_7)

Enter the number of rows: 3
Enter the number of columns: 3

Enter 9 values for Matrix 1
	(NOTE: Use space for separating the numbers)
	(NOTE:Your first 3  number/s would be the first row):
1 2 3 4 5 6 7 8 9

Matrix 4 is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------------
Enter the number of rows: 3
Enter the number of columns: 3

Enter 9 values for Matrix 1
	(NOTE: Use space for separating the numbers)
	(NOTE: Your first 3  number/s would be the first row):
9 8 7 6 5 4 3 2 1

Matrix 5 is:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
----------------------------------------------
Enter the number of rows: 3
Enter the number of columns: 3

Enter 9 values for Matrix 1
	(NOTE: Use space for separating the numbers)
	(NOTE: Your first 3  number/s would be the first row):
2 2 2 2 5 5 5 5 7

Matrix 6 is:
[[2 2 2]
 [2 5 5]
 [5 5 7]]
----------------------------------------------
Enter the number of rows: 4
Enter the number of columns: 4

Enter 16 values for Matrix 1
	(NOTE: Use space for

In [9]:
#Determines if the matrices are viable for operation and returns your own error message if they are not viable.
print('Matrix 4:')
mat_operations(mat_4)
print('\nMatrix 5:')
mat_operations(mat_5)
result1 = (mat_4.shape == mat_5.shape)
if result1:
  print('\nMatrix 4 and Matrix 5 are Viable for Operation')
else:
  print('\nMatrix 4 and Matrix 5 are Not Viable for Operation')

print('\n------------------------------------------------------')

print('Matrix 4:')
mat_operations(mat_4)
print('\nMatrix 6:')
mat_operations(mat_6)
result2 = (mat_4.shape == mat_6.shape)
if result2:
  print('\nMatrix 4 and Matrix 6 are Viable for Operation')
else:
  print('\nMatrix 4 and Matrix 6 are Not Viable for Operation')

print('\n------------------------------------------------------')

print('Matrix 5:')
mat_operations(mat_5)
print('\nMatrix 6:')
mat_operations(mat_6) 
result3 = (mat_5.shape == mat_6.shape)
if result3:
  print('\nMatrix 5 and Matrix 6 are Viable for Operation')
else:
  print('\nMatrix 5 and Matrix 6 are Not Viable for Operation')

print('\n------------------------------------------------------')

print('Matrix 4:')
mat_operations(mat_4)
print('\nMatrix 7:')
mat_operations(mat_7) 
result4 = (mat_4.shape == mat_7.shape)
if result4:
  print('\nMatrix 4 and Matrix 7 are Viable for Operation')
else:
  print('\nMatrix 4 and Matrix 7 are Not Viable for Operation')

Matrix 4:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 5:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix 4 and Matrix 5 are Viable for Operation

------------------------------------------------------
Matrix 4:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 6:
[[2 2 2]
 [2 5 5]
 [5 5 7]]

Matrix 4 and Matrix 6 are Viable for Operation

------------------------------------------------------
Matrix 5:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix 6:
[[2 2 2]
 [2 5 5]
 [5 5 7]]

Matrix 5 and Matrix 6 are Viable for Operation

------------------------------------------------------
Matrix 4:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 7:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 -9 -8 -7]
 [-6 -5 -4 -3]]

Matrix 4 and Matrix 7 are Not Viable for Operation


In [10]:
#Sum of the matrices

if result1:
  sum_1= mat_4 + mat_5
  print('Sum result 1:\n',sum_1)
else:
  print('Matrix 4 and Matrix 5 are Not Viable for Operation')

if result3:
  sum_2= mat_5 + mat_6
  print('\n\nSum result 2:\n',sum_2)
else:
  print('\n\nMatrix 5 and Matrix 6 are Not Viable for Operation')

if result4:
  sum_4= mat_4 + mat_7
  print('\n\nSum result 3:\n',sum_4)
else:
  print('\n\nMatrix 4 and Matrix 7 are Not Viable for Operation')

Sum result 1:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


Sum result 2:
 [[11 10  9]
 [ 8 10  9]
 [ 8  7  8]]


Matrix 4 and Matrix 7 are Not Viable for Operation


In [12]:
#Difference of the matrices

if result2:
  d_1= mat_4 - mat_6
  print('Difference result 1:\n',d_1)
else:
  print('Matrix 4 and Matrix 6 are Not Viable for Operation')

if result4:
  sum_4= mat_4 - mat_7
  print('\n\nDifference result 2:\n',sum_4)
else:
  print('\n\nMatrix 4 and Matrix 7 are Not Viable for Operation')

if result3:
  d_2= mat_5 - mat_6
  print('\n\nDifference result 3:\n',d_2)
else:
  print('\n\nMatrix 5 and Matrix 6 are Not Viable for Operation')

Difference result 1:
 [[-1  0  1]
 [ 2  0  1]
 [ 2  3  2]]


Matrix 4 and Matrix 7 are Not Viable for Operation


Difference result 3:
 [[ 7  6  5]
 [ 4  0 -1]
 [-2 -3 -6]]


In [13]:
#Element-wise multiplication of the matrices

if result1:
  m_1= mat_4 * mat_5
  print('Product result 1:\n',m_1)
else:
  print('Matrix 4 and Matrix 5 are Not Viable for Operation')

if result3:
  m_2= mat_5 * mat_6
  print('\n\nProduct result 2:\n',m_2)
else:
  print('\n\nMatrix 5 and Matrix 6 are Not Viable for Operation')

if result4:
  m_3= mat_4 * mat_7
  print('\n\nProduct result 3:\n',m_3)
else:
  print('\n\nMatrix 4 and Matrix 7 are Not Viable for Operation')

Product result 1:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Product result 2:
 [[18 16 14]
 [12 25 20]
 [15 10  7]]


Matrix 4 and Matrix 7 are Not Viable for Operation


In [14]:
#Element-wise division of the matrices

if result4:
  dv_3= mat_4 / mat_7
  print('Quotient result 1:\n',dv_3)
else:
  print('Matrix 4 and Matrix 7 are Not Viable for Operation')

if result2:
  dv_1= mat_4 / mat_6
  print('\n\nQuotient result 2:\n',dv_1)
else:
  print('\n\nMatrix 4 and Matrix 6 are Not Viable for Operation')

if result3:
  dv_2= mat_5 / mat_6
  print('\n\nQuotient result 3:\n',dv_2)
else:
  print('\n\nMatrix 5 and Matrix 6 are Not Viable for Operation')

Matrix 4 and Matrix 7 are Not Viable for Operation


Quotient result 2:
 [[0.5        1.         1.5       ]
 [2.         1.         1.2       ]
 [1.4        1.6        1.28571429]]


Quotient result 3:
 [[4.5        4.         3.5       ]
 [3.         1.         0.8       ]
 [0.6        0.4        0.14285714]]


## Conclusion

##Conclusion


> Matrix is a method or technique that is widely used in mathematics and physics to easier solve linear equations.[9] In this laboratory, the students gained knowledge about how the matrix can be applied to programming. They have learned that matrices can be: converted into a linear combination or LaTex Markdown, classified into zero matrix, identity matrix or ones matrix, and solved with different operations such as addition, subtraction, multiplication, and division. With the help of the functions and variables like NumPy or np, and “describe_mat(),” “mat_desc(),” & “mat_operations(),” the students were able to run programs that prints matrices and define them. 


> The world today adapted to the advancement of technology which increased human reliability, especially in the future. The current generation is welcomed in the world wherein they must be skilled and knowledgeable enough on technology to survive and work as a person. [10] This technology nowadays is composed of endless codes to make something work, including matrix. Therefore when technology has an emerging problem, it is only through itself also that it can be solved. One application that matrix can be used as a solution would be on Wireless Communication because it is a sensor that detects problems on wireless communication and its signal estimation. Matrices are said to be used as wireless signals(sensor arrays) in which the information is extracted and operated. The sensor arrays detect and locate the problem radiating provenance by the temporal and spatial information collected from the sensors. The matrices can help the process of illustrating digital images.[9]