<a href="https://colab.research.google.com/github/Mowee0/LinearAlgebra_2ndSem/blob/main/Assignment_4_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Laboratory 4: Matrix Operations
###Objective
1) Be familiar with the fundamental matrix operations.

2) Apply the operations to solve intermediate.

3) Apply matrix algebra in engineering solutions.

##Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


##Transposition
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 3&57&8&5\\-64&-13&20&6\\69&8&7&8\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 3&-64&69\\57&-13&8\\8&20&7\\5&6&8\end{bmatrix}$$

In [2]:
A = np.array ([
    [3, 57, 8, 5],
    [-64, -13, 20, 6],
    [69, 8, 7, 8]
])
A

array([[  3,  57,   8,   5],
       [-64, -13,  20,   6],
       [ 69,   8,   7,   8]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[  3, -64,  69],
       [ 57, -13,   8],
       [  8,  20,   7],
       [  5,   6,   8]])

In [4]:
AT2 = A.T
AT2

array([[  3, -64,  69],
       [ 57, -13,   8],
       [  8,  20,   7],
       [  5,   6,   8]])

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [98, 78, 65, 123, 98565],
    [65, 897, 16871, 656, 546],
    [12, 32, 46464, 789, 465]
])
B.shape

(3, 5)

In [7]:
np.transpose(B).shape

(5, 3)

In [8]:
B.T.shape

(5, 3)

**Try to create your own matrix (you can try non-squares) to test transposition**

In [16]:
C = np.array([
    [12, 34, 56, 78, 90],
    [21, 43, 65, 87, 9],
    [10, 29, 38, 47, 56],
    [1, 92, 83, 74, 65]
])

C

array([[12, 34, 56, 78, 90],
       [21, 43, 65, 87,  9],
       [10, 29, 38, 47, 56],
       [ 1, 92, 83, 74, 65]])

In [12]:
CT2 = C.T
CT2

array([[12, 21, 10,  1],
       [34, 43, 29, 92],
       [56, 65, 38, 83],
       [78, 87, 47, 74],
       [90,  9, 56, 65]])

In [17]:
C.shape

(4, 5)

In [13]:
np.transpose(B).shape

(5, 4)

##Dot Product/Inner Product
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [18]:
X = np.array([
    [4654, 5454, 5454],
    [3256, 789, 223],
    [4565, 543, 488]
])
Y = np.array([
    [8520, 7413],
    [2646, 565],
    [465, 987]
])

In [19]:
np.dot(X,Y)

array([[56619474, 42964710],
       [29932509, 24802614],
       [40557498, 34628796]])

In [20]:
X.dot(Y)

array([[56619474, 42964710],
       [29932509, 24802614],
       [40557498, 34628796]])

In [21]:
X @ Y

array([[56619474, 42964710],
       [29932509, 24802614],
       [40557498, 34628796]])

In [22]:
np.matmul(X,Y)

array([[56619474, 42964710],
       [29932509, 24802614],
       [40557498, 34628796]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}46546&21321&54654&4564&121&2165\\5&-2&1&5&3&5\\0&564654&32132&56465&454&3213\end{bmatrix}, B = \begin{bmatrix}9\\6\\21\\5\\1311\\54564\\54656\end{bmatrix}, C = \begin{bmatrix}1&2&3&4&5&6&7&8&9\\9&8&7&6&5&4&3&2&1\\-9&-8&-7&-6&-5&-4&-3&-2&-1\\-1&-2&-3&-4&-5&-6&-7&-8&-9\\0&0&0&0&0&0&0&0&0\\1&1&1&1&1&1&1&1&1\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [23]:
A = np.array([
    [46546, 21321, 54654, 4564, 121, 2165],
    [5, -2, 1, 5, 3, 5],
    [0, 564654, 32132, 56465, 454, 3213]
])
B = np.array([
    [9],
    [6],
    [21],
    [5],
    [1311],
    [54564],
    [54656]
])
C = np.array([
    [1, 2, 3, 4, 5, 6],
    [9, 8, 7, 6, 5, 4],
    [-9, -8, -7, -6, -5, -4],
    [-1, -2, -3, -4, -5, -6],
    [0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 6)
(7, 1)
(6, 6)


In [24]:
A @ C

array([[-255850, -180535, -105220,  -29905,   45410,  120725],
       [    -22,     -19,     -16,     -13,     -10,      -7],
       [4739446, 4150459, 3561472, 2972485, 2383498, 1794511]])

In [25]:
B @ C

ValueError: ignored

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [26]:
A @ C.T

array([[  285001,  1008709, -1008709,  -285001,        0,   129371],
       [      69,      101,     -101,      -69,        0,       17],
       [ 1473112,  5096068, -5096068, -1473112,        0,   656918]])

In [28]:
X = np.array([
    [9,-8,7,-6],
    [-5,4,-3,2]
])
Y = np.array([
    [15,87],
    [65,98],
    [12,53]
])
print(X.shape)
print(Y.shape)

(2, 4)
(3, 2)


In [30]:
X.T @ Y.T

array([[-300,   95, -157],
       [ 228, -128,  116],
       [-156,  161,  -75],
       [  84, -194,   34]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [47]:
A = np.array([
    [12,54,64],
    [46,78,46],
    [8,18,23]
])
B = np.array([
    [65,1213,643],
    [124,165,965],
    [313,343,383]
])
C = np.array([
    [131,313,10],
    [660,451,134],
    [112,302,112]
])

In [32]:
A @ B

array([[ 27508,  45418,  84338],
       [ 27060,  84446, 122466],
       [  9951,  20563,  31323]])

In [33]:
B @ A

array([[ 61722, 109698,  74747],
       [ 16798,  36936,  37721],
       [ 22598,  50550,  44619]])

In [34]:
np.array_equiv(A @ B, B @ A)

False

In [35]:
A @ (B@C)

array([[43025284, 54563598, 15806948],
       [72995412, 83539658, 25302556],
       [18383337, 21848122,  6363128]])

In [36]:
(A@B)@C

array([[43025284, 54563598, 15806948],
       [72995412, 83539658, 25302556],
       [18383337, 21848122,  6363128]])

In [37]:
np.array_equiv(A@(B@C),(A@B)@C)

True

In [38]:
A@(B+C)

array([[ 71888,  92856,  98862],
       [ 89718, 147914, 138530],
       [ 25455,  38131,  36391]])

In [39]:
A@B + A@C

array([[ 71888,  92856,  98862],
       [ 89718, 147914, 138530],
       [ 25455,  38131,  36391]])

In [40]:
np.array_equiv(A@(B+C),A@B + A@C)

True

In [41]:
(B+C)@A

array([[ 77772, 141366,  97759],
       [ 46536, 110166, 103789],
       [ 38730,  82170,  68255]])

In [42]:
B@A + C@A

array([[ 77772, 141366,  97759],
       [ 46536, 110166, 103789],
       [ 38730,  82170,  68255]])

In [43]:
np.array_equiv((B+C)@A,B@A + C@A)

True

In [44]:
A@np.eye(3)

array([[12., 54., 64.],
       [46., 78., 46.],
       [ 8., 18., 23.]])

In [45]:
np.array_equiv(A, A@np.eye(3))

True

In [91]:
D=np.array([])

In [92]:
A@D


ValueError: ignored

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##Determinant
A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [1,4,9,8,7],
    [0,3,5,3,4],
    [6,4,7,5,3],
    [4,6,4,7,8],
    [9,8,7,6,5]
])
np.linalg.det(A)

580.0000000000005

In [ ]:
A = np.array([
    [1,4,9],
    [0,3,5],
    [6,4,7],
  ])
np.linalg.det(A)

-41.00000000000001

In [ ]:
A = np.array([
    [54654,48654321],
    [9645524, 5412]
  ])
np.linalg.det(A)

-469296125121753.3

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

##Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [12423,7234,324123],
    [-3234, 523423,213423],
    [12312,234231,23423]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
P = np.array([
    [612,912321,1012, 213123],
    [123214, 1232, -12131,45435],
    [3123, 1236, 5437,45431],
    [23423,342643,346342,1345341]
])
Q = np.linalg.inv(P)
Q

array([[-2.68091749e-07,  8.75241819e-06, -3.10149285e-05,
         7.94229576e-07],
       [ 1.04944322e-06,  2.14103568e-07, -9.84526932e-06,
         1.58987311e-07],
       [-1.83280778e-06,  2.90767157e-06, -1.55077556e-04,
         5.42898187e-06],
       [ 2.09220898e-07, -9.55458703e-07,  4.29703297e-05,
        -7.08640834e-07]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
P = np.array([
    [612,912321,1012, 213123],
    [123214, 1232, -12131,45435],
    [3123, 1236, 5437,45431],
    [23423,342643,346342,1345341]
])
Q = np.linalg.inv(P)
Q

array([[-2.68091749e-07,  8.75241819e-06, -3.10149285e-05,
         7.94229576e-07],
       [ 1.04944322e-06,  2.14103568e-07, -9.84526932e-06,
         1.58987311e-07],
       [-1.83280778e-06,  2.90767157e-06, -1.55077556e-04,
         5.42898187e-06],
       [ 2.09220898e-07, -9.55458703e-07,  4.29703297e-05,
        -7.08640834e-07]])

In [ ]:
P@Q

array([[ 1.00000000e+00, -1.93472913e-17,  5.27782841e-16,
         3.54278942e-17],
       [-4.30308619e-18,  1.00000000e+00,  2.87787914e-17,
         6.17730541e-18],
       [ 1.20331618e-19,  3.12703388e-18,  1.00000000e+00,
         2.97679141e-18],
       [-6.54920051e-17,  2.43438328e-16, -7.51741741e-15,
         1.00000000e+00]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])